CREATE SEQUENCE seq_task;

CREATE TABLE TASK
(
    ID BIGINT PRIMARY KEY,
    DESCRIPTION VARCHAR (4096) NOT NULL,
    QUERY VARCHAR (4096) NOT NULL
);

INSERT INTO TASK(ID, DESCRIPTION, QUERY) VALUES (1, 'Description','SELECT ID, NAME, ROLE, YEARS FROM EMPLOYEES ORDER BY ID');

CREATE TABLE EMPLOYEES
(
   ID BIGINT PRIMARY KEY,
   NAME VARCHAR(256) NOT NULL,
   ROLE VARCHAR(128) NOT NULL,
   YEARS FLOAT NOT NULL
);

INSERT INTO EMPLOYEES(ID, NAME, ROLE, YEARS) VALUES (1, 'John Smith', 'Manager', 1.5);
INSERT INTO EMPLOYEES(ID, NAME, ROLE, YEARS) VALUES (2, 'John Doe', 'Engineer', 5.0);
INSERT INTO EMPLOYEES(ID, NAME, ROLE, YEARS) VALUES (3, 'Amanda Brown', 'Artist', 10.5);
INSERT INTO EMPLOYEES(ID, NAME, ROLE, YEARS) VALUES (4, 'Samantha Fox', 'Singer', 3.8);
INSERT INTO EMPLOYEES(ID, NAME, ROLE, YEARS) VALUES (5, 'Michael Johns', 'Manager', 7.0);
INSERT INTO EMPLOYEES(ID, NAME, ROLE, YEARS) VALUES (6, 'Oliver Stone', 'Engineer', 2.5);
INSERT INTO EMPLOYEES(ID, NAME, ROLE, YEARS) VALUES (7, 'Enrice Eaglesias', 'Singer', 8.5);

